### ISSUE TITLE
Problems detecting functions in psm1 file

### ISSUE THREAD

**Issue by jdhitsolutions** [MathieuBuisson/PSCodeHealth#10]
I'm not even sure how to report this but I'm trying to figure out why one module doesn't generate any report. The module works as expected. It has a manifest and all of the functions are in the psm1 file. Functions are exported using Export-ModuleMember in the .psm1 file and in the manifest. When I run Invoke-PSCodeHealth the only way I can get it to do anything is if I specify the path to the psm1 file. Yet I have other modules structured the same way that PSCodeHealth can process just fine.

Even running with -Verbose doesn't show me anything as the command never seems to get started. I suppose I could dig into your code to see what is happening but am hoping you have some troubleshooting tips. Or maybe Invoke-PSCodeHealth is making an assumption that I'm "breaking".

**Comment by jdhitsolutions** [comment]
In digging through your code I found the problem. My module uses 'Test ' in the name of its files which means no files are being found. Not quite sure how to work around this with your module.

**Comment by SeeminglyScience** [comment]
I ran into this issue as well. Since `Test` is an approved verb it's not unlikely a file name will contain it.

A possible solution is to parse files that match the filter and check for `Describe` blocks in the top level AST.

```powershell
$testFileAst.Find({
    param($Ast)
    $Ast -is [System.Management.Automation.Language.CommandAst] -and
    $Ast.GetCommandName() -eq 'Describe' -and
    $Ast.CommandElements.StaticType -contains [scriptblock]
}, $false)
```

**Comment by MathieuBuisson** [comment]
Hi Jeffery,

Yes, the function which gets the PowerShell files from the specified path does this :  
```powershell
$ChildItems.Where({$_.PSIsContainer -eq $False .... -and $_.BaseName -notmatch "Test"})
```

Which is not a clever way (to say the least) to filter out test files.  
I need to fix this.

Thanks for bringing this problem up.

**Comment by MathieuBuisson** [comment]
Hi @SeeminglyScience ,

You're right, any file containing `Pester` tests should match your filter.  
This is a much better way to exclude test scripts.  

Thanks a lot for your help.

**Comment by MathieuBuisson** [comment]
A fix for this problem is included in [this commit](https://github.com/MathieuBuisson/PSCodeHealth/commit/43b58152c92d1c0047abc6159762bcf320ff1e35).  
It is in version 0.2.9 of `PSCodeHealth`, which is available [in the PSGallery](https://www.powershellgallery.com/packages/PSCodeHealth/0.2.9).
