### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by pauby** [MathieuBuisson/PSCodeHealth#20]
There has been a PR sitting for 4 months and no updates to issues since October of 2017.

This isn't really the place for this comment. I'm just hoping it gets noticed.

**Comment by MathieuBuisson** [comment]
Hi @pauby ,

It is not abandoned, but spare time is limited.  
Also, I tend not to look at PRs which fail the build.  

Thank you for giving me a nudge, I'm gonna look into this PR.

**Comment by MathieuBuisson** [comment]
Hi @pauby ,  

Good news : the PR #15 has finally been merged.
Consequently, the issue #12  is solved and closed.

Thank you for your patience.
