### ISSUE TITLE
Can i run PSCodeHealth without test path ?

### ISSUE THREAD

**Issue by guptalakshay** [MathieuBuisson/PSCodeHealth#22]
---
name: Running PSCodeHealth without test cases.
about: Suggest an idea for this project
---

**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is.  
Ex. It is annoying when [...]  

**Describe the solution you would like**  
A clear description of what you want to happen.  

**Describe alternatives you have considered**  
A clear description of any alternative solutions or features you have considered.  

**Additional context**  
How is this affecting you ?  
Providing context helps us come up with a solution that is most useful and prioritize feature requests.

**Comment by MathieuBuisson** [comment]
Hi @guptalakshay ,

`TestsPath` itself is an optional parameter, if not specified it defaults to look for tests in the same location as the code being analyzed.  

If there are no tests in any location, then `Invoke-PSCodeHealth`'s intented behaviour is to run without error and the tests-related output values will be empty (or `0` for numeric values).

So the report generated by `PSCodeHealth` might be less useful without the tests-related information, but it should work fine.

**Comment by guptalakshay** [comment]
Thanks , appreciate the help.
