### ISSUE TITLE
Is there a way to give multiple folders and get their code health 

### ISSUE THREAD

**Issue by guptalakshay** [MathieuBuisson/PSCodeHealth#23]
---
name: Feature request
Is there a way to give multiple folders and get their code health ? For example : want to check for c:\folder1 and c:\folder2. If yes, then how to give comma separated or something else ? 
---

**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is.  
Ex. It is annoying when [...]  

**Describe the solution you would like**  
A clear description of what you want to happen.  

**Describe alternatives you have considered**  
A clear description of any alternative solutions or features you have considered.  

**Additional context**  
How is this affecting you ?  
Providing context helps us come up with a solution that is most useful and prioritize feature requests.

**Comment by MathieuBuisson** [comment]
Hi @guptalakshay ,

It is not possible to specify more than 1 code path.  
The assumption is that we should only analyzed 1 code base, or project, or set of **related** scripts at a time.  
This means the code should be logically organized in a specific file or folder.  

That said, it is easy to work around that, here is how :  

  - Put `folder1` and `folder2` in the same parent directory (for example : `code_repos`)

The directory structure will look like this :  
C:\code_repos
├───folder1
│       code.ps1
│       code.psm1
│
└───folder2  


  - Run `Invoke-PSCodeHealth` specifying the parent folder and `-Recurse` parameter, like so :  

```powershell
Invoke-PSCodeHealth -Path 'C:\code_repos' -Recurse
```  

Then, `Invoke-PSCodeHealth` will look for PowerShell code in the directory `C:\code_repos\` **and any subdirectories**, recursively.

**Comment by guptalakshay** [comment]
Sure thanks ! I understand the work around . Appreciate your help. The case that  i was referring is related scripts . One set in folder1  and another one in folder2, and we want to analyse both sets in one go. For now i will generate two reports by two runs.

**Comment by guptalakshay** [comment]
Hi @MathieuBuisson - This can really help us to get one set of reports for the multiple code bases. Do you want to prioritize this one ?
