### ISSUE TITLE
Doesn't seem to be listed on the PowerShell gallery any more

### ISSUE THREAD

**Issue by Tiberriver256** [MathieuBuisson/PSCodeHealth#4]
PS C:\windows\system32> Install-Module -Name PSCodeHealth -Repository PSGallery
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'PSCodeHealth'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by MathieuBuisson** [comment]
Thanks @Tiberriver256 for opening this issue.  
Actually, I had not published this module to the PowerShell gallery yet. Sorry about that.  

I just rectified this so you can now find the module there :  
https://www.powershellgallery.com/packages/PSCodeHealth  

And `Find-Module` can now find it :  

```powershell
Find-Module -Name PSCodeHealth -Repository PSGallery

Version    Name                                Repository           Description                              
-------    ----                                ----------           -----------                              
0.1.139    PSCodeHealth                        PSGallery            This module allows you to measure the ...
```

Please give it a try and let me know how it goes for you.

**Comment by Tiberriver256** [comment]
Installed perfectly. Thank you.

**Comment by MathieuBuisson** [comment]
Great !
Closing the issue, then.
