### ISSUE TITLE
Question about detected help

### ISSUE THREAD

**Issue by jdhitsolutions** [MathieuBuisson/PSCodeHealth#7]
When I run a report on a module and look at the per function details, the ContainsHelp entry shows false. Which I suppose is technically because there is not comment based help. But there is external help for the module. Are you testing for the existence of comment-based help only or are you taking external help into consideration?

**Comment by MathieuBuisson** [comment]
Hi Jeffery,

Yes this is using the `GetHelpContent` method of `FunctionDefinitionAst` objects and this method detect only comment-based help.  

Another limitation of that way of checking for help, is that it will only detect comment-based help which is **inside** the body of the function.  

For example, it will detect the help in this case :  
```powershell
Function MyFunction () {
<#
.SYNOPSIS
    This cmdlet configures nothing and does it remarkably well.
#>    
    Do-Nothing
}
```  
But not in this case :  
```powershell
<#
.SYNOPSIS
    This cmdlet configures nothing and does it remarkably well.
#>
Function MyFunction () {

    Do-Nothing
}
```

I could use `Get-Help` but it requires checking if there is a module and loading it, and this would work only for the **public** functions.  

Would you have any suggestions on how to better handle the detection of help ?

Thank you.

**Comment by jdhitsolutions** [comment]
I'm not sure about private functions. Since they are only read when editing the module, I would trust the author has enough general comments. I guess I wouldn't worry about those functions. As for public functions, any external help will be an a culture specific folder which you could test for. The file should be called <modulename>-help.xml.  You could parse the XML looking for matching names.

```
PS C:\>[xml]$h = get-content c:\scripts\mylmhost\en-us.\Mylmhost-help.xml
PS C:\>$h.helpitems.command.details.name
Get-LmhostsEntry
Remove-LmhostsEntry
Set-LmhostsEntry
```
You might want to differentiate between comment based help detected or not and external help.

**Comment by SeeminglyScience** [comment]
@MathieuBuisson If you go the `Get-Help` route and want to test private functions you can do something like this:

```powershell
$module = Get-Module ModuleName
& $module { Get-Help PrivateFunctionName -Category Function }
```

Also the `GetHelpContent` method does work for CBH outside the function definition as long as it's included in a parent AST.  I didn't have any issues getting PSCodeHealth to detect CBH in the example you gave.  Is it possible that when you initially tested, it may have been with one of the ASTs that are re-parsed in some of the other private functions?

**Comment by MathieuBuisson** [comment]
Hi @SeeminglyScience ,

Well, I haven't actually tested it GetHelpContent against a function which has comment-based help in the parent.  
I just assumed it wouldn't find it.
So if it works in this scenario, then it means that this method is more clever than I thought and it is good news.  

Thanks.

**Comment by MathieuBuisson** [comment]
Hi Jeffery,  

Thanks for your **help** on this (pun not intended).  
This has been way more complicated than I expected and it's a pain to unit test, but I managed to make it work.  

The function `Test-FunctionHelpCoverage` now returns `$True` if there is comment-based help **OR** if there is a command with the same name listed in an external help file. It uses the technique you showed above to parse the XML content (or MAML).  

You can have a look at the commit referenced above this comment to view the code changes.  

Could you give it a try with version 0.2.7 of `PSCodeHealth` available [in the PSGallery](https://www.powershellgallery.com/packages/PSCodeHealth/0.2.7) and let me know if it's OK ?  

Thank you.

**Comment by jdhitsolutions** [comment]
This looks like it works for me on a few modules that I tested.

**Comment by MathieuBuisson** [comment]
@jdhitsolutions ,
That's great.  
I'm gonna close this issue then.
Thanks again.
